[metadata]
name = "alias"
description = "Fast shell alias search"
requirements = ["bat"]

[source]
# Run this once to get the list
command = "$SHELL -ic 'alias'"
output = "{split:=:0}"

[preview]
# Use 'typeset' or 'alias' directly without the -ic overhead if possible
# TODO: consider adjusting this
command = "echo {} | bat -l bash --color=always --style=plain" 

[ui]
layout = "portrait"

[ui.preview_panel]
header = "-"
size = 40
