return {}
-- Commands work; something is off with the keymapping descriptions
-- return {
--   "MoaidHathot/dotnet.nvim",
--   cmd = "DotnetUI",
--   opts = {
--     -- bootstrap = {
--     --   auto_bootstrap = true, -- Automatically call "bootstrap" when creating a new file, adding a namespace and a class to the files
--     -- },
--     -- project_selection = {
--     --   path_display = "filename_first", -- Determines how file paths are displayed. All of Telescope's path_display options are supported
--     -- },
--   },
--   keys = {
--     {
--       "<leader>Na",
--       "<cmd>:DotnetUI new_item<CR>",
--       mode = { "n" },
--       { desc = "NET new item", silent = true },
--     },
--     {
--       "<leader>Nb",
--       "<cmd>:DotnetUI file bootstrap<CR>",
--       mode = { "n" },
--       { desc = ".NET bootstrap class", silent = true },
--     },
--     {
--       "<leader>Nra",
--       "<cmd>:DotnetUI project reference add<CR>",
--       mode = { "n" },
--       { desc = ".NET add project reference", silent = true },
--     },
--     {
--       "<leader>Nrr",
--       "<cmd>:DotnetUI project reference remove<CR>",
--       mode = { "n" },
--       { desc = ".NET remove project reference", silent = true },
--     },
--     -- { "<leader>Np",  { desc = "packages", silent = true } },
--     {
--       "<leader>Npa",
--       "<cmd>:DotnetUI project package add<CR>",
--       mode = { "n" },
--       { desc = ".NET ada project package", silent = true },
--     },
--     {
--       "<leader>Npr",
--       "<cmd>:DotnetUI project package remove<CR>",
--       mode = { "n" },
--       { desc = ".NET remove project package", silent = true },
--     },
--   },
-- }
